### ISSUE TITLE
The injected service is not the same instance

### ISSUE THREAD

**Issue by quanjialiang** [tarangkhandelwal/components-by-selector#1]
import { Injectable } from '@angular/core';

@Injectable()
export class Dynamic1Service {
    count = 1;
}

@NgModule({
  imports: [CommonModule],
  declarations: [Dynamic1Component],
  providers: [Dynamic1Service]
})
export class Child1Module extends BaseModule {
  dynamicComponents = [Dynamic1Component];

  constructor(componentFactoryResolver: ComponentFactoryResolver) {
    super(componentFactoryResolver);
  }
}

export class Dynamic1Component implements OnInit {

  constructor(public dynamic1Service: Dynamic1Service) { }

  ngOnInit() {
    console.log(this.dynamic1Service.count);
    this.dynamic1Service.count++;
  }

}
This log is always 1，How to make the injected service be the same instance？

**Comment by tarangkhandelwal** [comment]
providedIn: root should help have singleton service instance I think here

**Comment by quanjialiang** [comment]
Thank you，Perfectly solved this problem。But I use angular5, which does not support providedIn: "root", is there any other way?For example, using forRoot, how can I change it?
export class Child1Module extends BaseModule {
  dynamicComponents = [Dynamic1Component];

  constructor(componentFactoryResolver: ComponentFactoryResolver) {
    super(componentFactoryResolver);
  }

  static forRoot(): ModuleWithProviders {
    return <ModuleWithProviders>{
      ngModule: Child1Module,
      providers: [
        Dynamic1Service,
      ],
    };
  }
}

**Comment by tarangkhandelwal** [comment]
This particular repository is meant for angular 9+ and IVY with AOT compilation.

Your query is unrelated to the repository.

Around your query this might help:
https://stackoverflow.com/questions/48186872/angular-lazy-loading-modules-with-services
