### ISSUE TITLE
Add example of component with inputs

### ISSUE THREAD

**Issue by gbrunow** [tarangkhandelwal/components-by-selector#2]
The article [Rendering dynamic components by selector name in Ivy](https://indepth.dev/posts/1400/components-by-selector-name-angular) talks about some custom binding functionality provided by the `DynamicSelectorComponent` but the sample component doesn't have any inputs.

I've been playing around with the stackblitz and still haven't been able to figure out how to work with inputs.

**Comment by tarangkhandelwal** [comment]
Thanks for opening the issue.

I have updated the example to include the inputs passed to a component rendered via a selector.

```
<app-dynamic-selector *ngIf="showComponent"
[inputs]="{inputValue: 'My Input Value'}"
[componentSelector]="'app-dynamic1'"
[moduleLoaderFunction]="getModuleLoader()"
></app-dynamic-selector>
```

Commit:
#https://github.com/tarangkhandelwal/components-by-selector/commit/7791db29ef0f1f15200a0d4fd65d4a4a2cd95e34

**Comment by gbrunow** [comment]
Thanks @tarangkhandelwal!
Great job, by the way.

**Comment by gbrunow** [comment]
FYI, the stackblitz seems to be broken now.

**Comment by tarangkhandelwal** [comment]
> FYI, the stackblitz seems to be broken now.

I will try to check & fix why this isn't working in stackblitz. But it should work locally.
